package atom

type AtomMasterCommandTable struct {
	Header                          AtomCommonTableHeader
	ASICInit                        uint16
	GetDisplaySurfaceSize           uint16
	ASICRegistersInit               uint16
	VRAMBlockVenderDetection        uint16
	DIGxEncoderControl              uint16
	MemoryControllerInit            uint16
	EnableCRTCMemReq                uint16
	MemoryParamAdjt                 uint16
	DVOEncoderControl               uint16
	GPIOPinControl                  uint16
	SetEngineClock                  uint16
	SetMemoryClock                  uint16
	SetPixelClock                   uint16
	EnableDispPowerGating           uint16
	ResetMemoryDLL                  uint16
	ResetMemoryDevice               uint16
	MemoryPLLInit                   uint16
	AdjtDisplayPll                  uint16
	AdjtMemoryController            uint16
	EnableASICStaticPwrMgt          uint16
	SetUniphyInstance               uint16
	DACLoadDetection                uint16
	LVTMAEncoderControl             uint16
	HWMiscOperation                 uint16
	DAC1EncoderControl              uint16
	DAC2EncoderControl              uint16
	DVOOutputControl                uint16
	CV1OutputControl                uint16
	GetConditionalGoldenSetting     uint16
	TVEncoderControl                uint16
	PatchMCSetting                  uint16
	MCSEQControl                    uint16
	GfxHarvesting                   uint16
	EnableScaler                    uint16
	BlankCRTC                       uint16
	EnableCRTC                      uint16
	GetPixelClock                   uint16
	EnableVGARender                 uint16
	GetSCLKOverMCLKRatio            uint16
	SetCRTCTiming                   uint16
	SetCRTCOverScan                 uint16
	SetCRTCReplication              uint16
	SelectCRTCSource                uint16
	EnableGraphSurfaces             uint16
	UpdateCRTCDoubleBufferRegisters uint16
	LUTAutoFill                     uint16
	EnableHWIconCursor              uint16
	GetMemoryClock                  uint16
	GetEngineClock                  uint16
	SetCRTCingDTDTiming             uint16
	ExternalEncoderControl          uint16
	LVTMAOutputControl              uint16
	VRAMBlockDetectionByStrap       uint16
	MemoryCleanUp                   uint16
	ProcessI2cChannelTransaction    uint16
	WriteOneByteToHWAssistedI2C     uint16
	ReadHWAssistedI2CStat           uint16
	SpeedFanControl                 uint16
	PowerConnectorDetection         uint16
	MCSynchronization               uint16
	ComputeMemoryEnginePLL          uint16
	MemoryRefreshConversion         uint16
	VRAMGetCurrentInfoBlock         uint16
	DynamicMemorySettings           uint16
	MemoryTraining                  uint16
	EnableSpreadSpectrumOnPPLL      uint16
	TMDSAOutputControl              uint16
	SetVoltage                      uint16
	DAC1OutputControl               uint16
	DAC2OutputControl               uint16
	ComputeMemoryClockParam         uint16
	ClockSource                     uint16
	MemoryDeviceInit                uint16
	GetDispObjectInfo               uint16
	DIG1EncoderControl              uint16
	DIG2EncoderControl              uint16
	DIG1TransmitterControl          uint16
	DIG2TransmitterControl          uint16
	ProcessAuxChannelTransaction    uint16
	DPEncoderService                uint16
	GetVoltageInfo                  uint16
}